// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7t5ZXHWHaTwtZCNfNH8F6VBHBlFIASqM',
    appId: '1:568258525832:web:1110b3980590c354547d3d',
    messagingSenderId: '568258525832',
    projectId: 'muheeb-backend-sky',
    authDomain: 'muheeb-backend-sky.firebaseapp.com',
    storageBucket: 'muheeb-backend-sky.firebasestorage.app',
    measurementId: 'G-E5E1S2XJ47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyOXFGJ8UMjJNovTUE1LsuZ8TODCf9OlE',
    appId: '1:568258525832:android:3142bf30fcd35a8c547d3d',
    messagingSenderId: '568258525832',
    projectId: 'muheeb-backend-sky',
    storageBucket: 'muheeb-backend-sky.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCujpjP7J4ycv2lA094GqBV3BRM3-8jjHQ',
    appId: '1:568258525832:ios:1f1dfec563672555547d3d',
    messagingSenderId: '568258525832',
    projectId: 'muheeb-backend-sky',
    storageBucket: 'muheeb-backend-sky.firebasestorage.app',
    iosBundleId: 'com.example.skyzIslamabadzBackend',
  );
}
